### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Kncuk** [THUDM/ImageReward#23]
Attached is the error I got, I suppose it has to do with the version of SD that I'm using which is [automatic by vlad](https://github.com/vladmandic/automatic)
Could this be fix here or should this be done on that SD's end?
![image](https://github.com/THUDM/ImageReward/assets/79404196/13008e7e-093e-438a-8727-cf1f078aee31)
Thanks

**Comment by tongyx361** [comment]
Thank you so much for the issue! Let's resolve it together 😀

**Did you have "Filter out images with low scores" turned on?**

If so, the reason for this error would be that `imgs` became an empty list `[]` due to **all generated images with low scores below "Lower score limit"**, which eventually led to `list (zip(*img_info_list)` becoming an empty list.
This is indeed a design oversight on my part, and I am very sorry.

You can avoid the error and get meaningful results by now by **setting the "Lower score limit" for the images to a lower value**, which may allow some of the images to be unfiltered.

**To avoid the error completely, even if all images are filtered out**, you can try replacing in `image_reward.py`

```Python
        # append score to info
        infotexts = [img.info["parameters"] for img in imgs]

        # sort to score
        img_info_list = list(zip(imgs, infotexts))
        img_info_list.sort(key=lambda x: x[0].info["score"], reverse=True)
        imgs, infotexts = list(zip(*img_info_list))
```

with

```Python
        if len(imgs) > 0.
            # append score to info
            infotexts = [img.info["parameters"] for img in imgs]

            # sort to score
            img_info_list = list(zip(imgs, infotexts))
            img_info_list.sort(key=lambda x: x[0].info["score"], reverse=True)
            imgs, infotexts = list(zip(*img_info_list))
        else: # len(imgs) == 0
            infotexts = []
```

This should help.
