### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by Sniper199999** [THUDM/ImageReward#29]
I use Automatic1111 and the requirements are constantly updating. Image Browser uses outdated requirements of following packages:
1. Accelerate
2. diffusers
3. huggingface-hub
4. transformers

[Another issue opened in A1111 repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11456)

PIP Error:
`Installing collected packages: transformers
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
image-reward 1.3 requires accelerate==0.16.0, but you have accelerate 0.19.0 which is incompatible.
image-reward 1.3 requires diffusers==0.16.0, but you have diffusers 0.16.1 which is incompatible.
image-reward 1.3 requires huggingface-hub==0.13.4, but you have huggingface-hub 0.15.1 which is incompatible.
image-reward 1.3 requires transformers==4.27.4, but you have transformers 4.30.2 which is incompatible.
Successfully installed transformers-4.30.2`

I suggest to bump the requirements.txt to current and future releases of these packages.

**Comment by xujz18** [comment]
Thanks for your suggestion! We have update it, thanks a lot.

**Comment by DoughyInTheMiddle** [comment]
As info...this is broken again/still. I say still only because some of these are the same version mismatches as previously, and others have updated because A1111 just charges like a blind bull.

image-reward 1.3 requires accelerate==0.16.0, but you have accelerate 0.20.3 which is incompatible.
image-reward 1.3 requires datasets==2.11.0, but you have datasets 2.13.1 which is incompatible.
image-reward 1.3 requires diffusers==0.16.0, but you have diffusers 0.19.0 which is incompatible.
image-reward 1.3 requires fairscale==0.4.13, but you have fairscale 0.4.4 which is incompatible.
image-reward 1.3 requires huggingface-hub==0.13.4, but you have huggingface-hub 0.15.1 which is incompatible.
image-reward 1.3 requires transformers==4.27.4, but you have transformers 4.31.0 which is incompatible.

**Comment by Sniper199999** [comment]
> As info...this is broken again/still. I say still only because some of these are the same version mismatches as previously, and others have updated because A1111 just charges like a blind bull.
> 
> image-reward 1.3 requires accelerate==0.16.0, but you have accelerate 0.20.3 which is incompatible. image-reward 1.3 requires datasets==2.11.0, but you have datasets 2.13.1 which is incompatible. image-reward 1.3 requires diffusers==0.16.0, but you have diffusers 0.19.0 which is incompatible. image-reward 1.3 requires fairscale==0.4.13, but you have fairscale 0.4.4 which is incompatible. image-reward 1.3 requires huggingface-hub==0.13.4, but you have huggingface-hub 0.15.1 which is incompatible. image-reward 1.3 requires transformers==4.27.4, but you have transformers 4.31.0 which is incompatible.

U need to just update ImageReward to new version. Here: https://pypi.org/project/image-reward/ . The problem comes from Image Browser Extension, they haven't updated the requirements for ImageReward from v1.3 to the newer versions i.e v1.5.
